project_path: "\\" # PATH TO PROJECT
excluded_dirs: ["bin", "obj", ".git", ".config", ".idea", "node_modules", "Migrations"]

chunk_size: 1200
chunk_overlap: 200

model: "llama3.2:3b"
embed_model: "nomic-embed-text"

rerank_candidates: 14
rerank_select: 6